# Generated by Django 2.1.7 on 2019-02-28 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsConfirmed', models.BooleanField()),
                ('ReceivingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FriendReceiver', to=settings.AUTH_USER_MODEL)),
                ('SendingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FriendSender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('MessageBody', models.CharField(max_length=1000)),
                ('DateSent', models.DateTimeField(auto_now=True)),
                ('ReceivingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageReceiver', to=settings.AUTH_USER_MODEL)),
                ('SendingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageSender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostBody', models.CharField(max_length=1000)),
                ('DateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThreadTitle', models.CharField(max_length=100)),
                ('ThreadBody', models.CharField(max_length=1000)),
                ('ViewCount', models.IntegerField()),
                ('DateStarted', models.DateField()),
                ('PostCount', models.IntegerField()),
                ('DateUpdate', models.DateField()),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicTitle', models.CharField(max_length=100)),
                ('DateUpdated', models.DateField()),
                ('ThreadCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Signature', models.CharField(max_length=200, null=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.Topic'),
        ),
        migrations.AddField(
            model_name='post',
            name='Thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.Thread'),
        ),
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
