# Generated by Django 2.1.7 on 2019-03-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Avatar',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
