# Generated by Django 2.1.7 on 2019-03-08 00:14

import Forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_TestDataLoad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Avatar',
            field=models.ImageField(blank=True, default='avatar/default-avatar.png', upload_to=Forum.models.user_directory_path),
        ),
    ]
