# Generated by Django 2.1.7 on 2019-03-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_auto_20190308_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-DateUpdate']},
        ),
    ]
