# Generated by Django 2.1.7 on 2019-03-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0006_auto_20190308_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='UpVoteCount',
            field=models.IntegerField(default=0),
        ),
    ]
