# Generated by Django 2.1.7 on 2019-03-19 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0009_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAdded', models.DateField()),
                ('Title', models.CharField(max_length=25)),
                ('Body', models.CharField(max_length=1000)),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'DateAdded',
            },
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='Author',
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
