# Generated by Django 2.1.7 on 2019-03-20 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0010_auto_20190319_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupUrl', models.CharField(max_length=20)),
                ('GroupName', models.CharField(max_length=50)),
                ('DateUpdated', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
