# Generated by Django 2.1.7 on 2019-03-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0011_meetupgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupgroup',
            name='GroupUrl',
            field=models.CharField(max_length=150),
        ),
    ]
